#!/usr/bin/env bun
/**
 * Bootstrap a new locale catalog by seeding every existing `en.json`
 * key with a user-supplied translation, then:
 *
 *   1. write `src/locales/<code>.json`
 *   2. add `<code>` to `SUPPORTED_LOCALES` in `src/mapping.ts`
 *   3. regenerate `src/loaders.ts` so Metro picks up the new chunk
 *
 * Invocation:
 *   bun scripts/add-locale.ts payload.json
 *   bun scripts/add-locale.ts < payload.json
 *   bun scripts/add-locale.ts --stdin
 *
 * Payload shape:
 *   {
 *     "locale": "fr",
 *     "translations": { "app.name": "Jellyfuse", "home.play": "Lire", ... }
 *   }
 *
 * Rules:
 *   - `locale` must be a 2-letter BCP-47 primary subtag (we don't model
 *     region-specific variants at the catalog level yet).
 *   - `translations` must contain *every* key in `en.json`; extras
 *     abort the run so stray keys don't drift.
 *   - Locale must not already exist — rerun with `--force` to overwrite
 *     the catalog (mapping + loaders are idempotent so they won't
 *     duplicate).
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

interface Payload {
  locale: string;
  translations: Record<string, string>;
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(scriptDir, "..");
const srcDir = join(pkgDir, "src");
const localesDir = join(srcDir, "locales");
const mappingPath = join(srcDir, "mapping.ts");
const loadersPath = join(srcDir, "loaders.ts");

function parseArgs(argv: string[]): { file: string | null; force: boolean } {
  let file: string | null = null;
  let force = false;
  for (const arg of argv.slice(2)) {
    if (arg === "--force") force = true;
    else if (arg === "--stdin") file = null;
    else if (!arg.startsWith("--")) file = arg;
  }
  return { file, force };
}

function readPayload(file: string | null): Payload {
  const raw = file ? readFileSync(file, "utf8") : readFileSync(0, "utf8");
  const parsed: unknown = JSON.parse(raw);
  if (
    !parsed ||
    typeof parsed !== "object" ||
    typeof (parsed as Payload).locale !== "string" ||
    !(parsed as Payload).translations ||
    typeof (parsed as Payload).translations !== "object"
  ) {
    throw new Error("Payload must be { locale: string, translations: Record<string, string> }");
  }
  const p = parsed as Payload;
  if (!/^[a-z]{2,3}$/.test(p.locale)) {
    throw new Error(
      `Invalid locale "${p.locale}" — expected a 2-3 letter BCP-47 primary subtag (e.g. "fr").`,
    );
  }
  return p;
}

function loadEnglish(): Record<string, string> {
  return JSON.parse(readFileSync(join(localesDir, "en.json"), "utf8")) as Record<string, string>;
}

function sortedJson(data: Record<string, string>): string {
  const sorted: Record<string, string> = {};
  for (const k of Object.keys(data).sort((a, b) => a.localeCompare(b))) {
    sorted[k] = data[k]!;
  }
  return `${JSON.stringify(sorted, null, 2)}\n`;
}

function readMapping(): string {
  return readFileSync(mappingPath, "utf8");
}

function updateMapping(src: string, locales: string[]): string {
  const match = /export const SUPPORTED_LOCALES = \[[^\]]*\] as const;/.exec(src);
  if (!match) {
    throw new Error("Could not find SUPPORTED_LOCALES declaration in mapping.ts");
  }
  const literal = locales.map((l) => `"${l}"`).join(", ");
  const replacement = `export const SUPPORTED_LOCALES = [${literal}] as const;`;
  return src.replace(match[0], replacement);
}

function existingLocalesFromMapping(src: string): string[] {
  const match = /export const SUPPORTED_LOCALES = \[([^\]]*)\] as const;/.exec(src);
  if (!match) return [];
  return [...match[1]!.matchAll(/"([^"]+)"/g)].map((m) => m[1]!);
}

function writeLoaders(locales: string[]): void {
  const entries = [...locales]
    .sort((a, b) => a.localeCompare(b))
    .map((l) => `  ${l}: () => import("./locales/${l}.json").then((m) => m.default),`)
    .join("\n");
  const body = `// Generated by \`packages/i18n/scripts/add-locale.ts\`. Keeping this
// file stable across edits is load-bearing — Metro chunks every
// dynamic \`import()\` into its own async bundle, so only the active
// locale's JSON is fetched at runtime.
//
// If you edit this by hand, keep entries alphabetized and mirror
// \`SUPPORTED_LOCALES\` in \`mapping.ts\`.

export const catalogLoaders: Record<string, () => Promise<Record<string, string>>> = {
${entries}
};
`;
  writeFileSync(loadersPath, body, "utf8");
}

function main(): void {
  const { file, force } = parseArgs(process.argv);
  const payload = readPayload(file);

  const english = loadEnglish();
  const enKeys = new Set(Object.keys(english));
  const payloadKeys = new Set(Object.keys(payload.translations));

  const missing = [...enKeys].filter((k) => !payloadKeys.has(k));
  const extra = [...payloadKeys].filter((k) => !enKeys.has(k));
  if (missing.length > 0) {
    throw new Error(`Missing translations for ${missing.length} key(s): ${missing.join(", ")}`);
  }
  if (extra.length > 0) {
    throw new Error(`Unknown keys not present in en.json: ${extra.join(", ")}`);
  }
  for (const [k, v] of Object.entries(payload.translations)) {
    if (typeof v !== "string" || v.length === 0) {
      throw new Error(`Empty translation for "${k}"`);
    }
  }

  const localePath = join(localesDir, `${payload.locale}.json`);
  if (existsSync(localePath) && !force) {
    throw new Error(`${payload.locale}.json already exists — rerun with --force to overwrite`);
  }
  writeFileSync(localePath, sortedJson(payload.translations), "utf8");

  const mappingSrc = readMapping();
  const existing = new Set(existingLocalesFromMapping(mappingSrc));
  existing.add(payload.locale);
  if (!existing.has("en")) existing.add("en");
  const nextLocales = [...existing].sort((a, b) => a.localeCompare(b));
  writeFileSync(mappingPath, updateMapping(mappingSrc, nextLocales), "utf8");

  writeLoaders(nextLocales);

  console.log(`added ${payload.locale}: ${Object.keys(payload.translations).length} keys`);
  console.log(`SUPPORTED_LOCALES → [${nextLocales.map((l) => `"${l}"`).join(", ")}]`);
}

main();
