// Generated by `packages/i18n/scripts/add-locale.ts`. Keeping this
// file stable across edits is load-bearing — Metro chunks every
// dynamic `import()` into its own async bundle, so only the active
// locale's JSON is fetched at runtime.
//
// If you edit this by hand, keep entries alphabetized and mirror
// `SUPPORTED_LOCALES` in `mapping.ts`.

export const catalogLoaders: Record<string, () => Promise<Record<string, string>>> = {
  en: () => import("./locales/en.json").then((m) => m.default),
  fr: () => import("./locales/fr.json").then((m) => m.default),
};
